name: project cicd flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:  # Workflow-level permissions
  contents: write  # Required for dependency graph submission
  security-events: write  # Keep this if you plan to integrate security tools later

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        # Optionally specify the directory if your pom.xml isn’t in the root
        # with:
        #   directory: "./"

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dunqooop/springboot-image
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}